# (c) 2011-2014 Peter Althainz
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


# scons file to build HGamer3DEnet library, version 0.3.0

from os.path import expanduser, exists
home = expanduser("~")
import os, sys 

# settings
home = expanduser("~")
libpath = home + "/.HGamer3D/lib"

# environment
env = Environment() 
if env["PLATFORM"] == "win32":
   env = Environment(TARGET_ARCH="x86", MSVC_VERSION="10.0") 
   env.MergeFlags({"CCFLAGS" : "/DWIN32 /D_WIN32 /DHGamer3DEnet030_EXPORTS /EHsc /MD"})

# env["ENV"]["PATH"] = os.environ.get("PATH")

# include path, libpath

if env["PLATFORM"] == "win32":

   env.Append(CPPPATH=["include","../Deps/include","../deps/include"])
   env.Append(LIBPATH=["lib","../Deps/lib","../Deps/lib"])
   env.SharedLibrary("hg3denet030", ["ClassEnet.cpp","ClassEnetPacket.cpp","ClassEnetClient.cpp","hg3denet.cpp","ClassEnetServer.cpp","ClassPtr.cpp"], LIBS = ["enet137.lib","winmm.lib","ws2_32.lib"])
   env.Alias('install', libpath)
   env.Install(libpath, "hg3denet030.dll")

else:
   env.Append(CPPPATH=["include","../Deps/include","../deps/include"])
   env.Append(LIBPATH=["lib","../Deps/lib","../Deps/lib"])
   env.SharedLibrary("hg3denet030", ["ClassEnet.cpp","ClassEnetPacket.cpp","ClassEnetClient.cpp","hg3denet.cpp","ClassEnetServer.cpp","ClassPtr.cpp"], LIBS = [":libenet.so.2"])
   env.Alias('install', libpath)
   env.Install(libpath, "libhg3denet030.so")


