# (c) 2011-2014 Peter Althainz
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


# scons file to build HGamer3DEnet library, version 0.4.0


# set environment
#################
from os.path import expanduser, exists
import os, sys
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

libpath = home + "/.HGamer3D/lib"

if env["PLATFORM"] == "win32":
   # on windows, create new environment, which finds MS C-Compiler
   env = Environment(TARGET_ARCH="x86", MSVC_VERSION="10.0")
   env.MergeFlags({"CCFLAGS" : "/DWIN32 /D_WIN32 /DHGamer3DEnet040_EXPORTS /EHsc /MD"})

# set other compile parameters
##############################

if env["PLATFORM"] == "win32":

   env.Append(CPPPATH=["include","../Deps/include","../deps/include"])
   env.Append(LIBPATH=["lib","../Deps/lib","../Deps/lib"])
   env.SharedLibrary("hg3denet040", ["ClassEnet.cpp","ClassEnetServer.cpp","ClassEnetClient.cpp","ClassEnetPacket.cpp","ClassPtr.cpp","hg3denet.cpp"], LIBS = ["enet137.lib","winmm.lib","ws2_32.lib"])
   env.Alias('install', libpath)
   env.Install(libpath, "hg3denet040.dll")

else:
   env.Append(CPPPATH=["include","../Deps/include","../deps/include"])
   env.Append(LIBPATH=["lib","../Deps/lib","../Deps/lib"])
   env.SharedLibrary("hg3denet040", ["ClassEnet.cpp","ClassEnetServer.cpp","ClassEnetClient.cpp","ClassEnetPacket.cpp","ClassPtr.cpp","hg3denet.cpp"], LIBS = ["enet"])
   env.Alias('install', libpath)
   env.Install(libpath, "libhg3denet040.so")


