# (c) 2011-2014 Peter Althainz
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


# scons file to build HGamer3DSDL2 library, version 0.4.0


# set environment
#################
from os.path import expanduser, exists
import os, sys
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

libpath = home + "/.HGamer3D/lib"

if env["PLATFORM"] == "win32":
   # on windows, create new environment, which finds MS C-Compiler
   env = Environment(TARGET_ARCH="x86", MSVC_VERSION="10.0")
   env.MergeFlags({"CCFLAGS" : "/DWIN32 /D_WIN32 /DHGamer3DSDL2040_EXPORTS /EHsc /MD"})

# set other compile parameters
##############################

if env["PLATFORM"] == "win32":

   env.Append(CPPPATH=["include","../Deps/include","../Deps/include","../Deps/lib/include"])
   env.Append(LIBPATH=["lib","../Deps/lib","../Deps/lib"])
   env.SharedLibrary("hg3dsdl2040", ["HeaderSDLVideo.cpp","HeaderSDLEvents.cpp","HeaderSDLKeyboard.cpp","ClassHG3DUtilities.cpp","HG3DUtilities.cpp","ClassPtr.cpp","HeaderSDLMouse.cpp","HeaderSDL.cpp"], LIBS = ["SDL2.lib"])
   env.Alias('install', libpath)
   env.Install(libpath, "hg3dsdl2040.dll")

else:
   env.Append(CPPPATH=["include","../Deps/include","../Deps/include","../Deps/lib/include"])
   env.Append(LIBPATH=["lib","../Deps/lib","../Deps/lib"])
   env.SharedLibrary("hg3dsdl2040", ["HeaderSDLVideo.cpp","HeaderSDLEvents.cpp","HeaderSDLKeyboard.cpp","ClassHG3DUtilities.cpp","HG3DUtilities.cpp","ClassPtr.cpp","HeaderSDLMouse.cpp","HeaderSDL.cpp"], LIBS = ["SDL2-2.0","X11"])
   env.Alias('install', libpath)
   env.Install(libpath, "libhg3dsdl2040.so")


