# configure, build, install the examples

# set environment
#################
from os.path import expanduser
import os
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

# the output directory
env.Command("build", "", Mkdir("build"))


for (p, s) in [

    # the BaseAPI examples

    ("BaseAPI", "Audio"),
    ("BaseAPI", "BlueCube"),
    ("BaseAPI", "BumpMappingCube"),
    ("BaseAPI", "GUI-Widgets"),
    ("BaseAPI", "Joystick"),
    ("BaseAPI", "Keyboard"),
    ("BaseAPI", "Mouse"),
    ("BaseAPI", "Network-Chat"),
    ("BaseAPI", "WinEvent"),

    # first EcsAPI examples

    ("EcsAPI", "RotatePlaton"),
    ("EcsAPI", "Coordinates"),
    ("EcsAPI", "GUI-Switch")

]:
    env.Command("build/" + s, [p + "/" + s + ".hs",
                               "build/.HGamer3D"
                               ] , "rm -f build/*.o && " + "ghc --make -threaded -odir build -hidir build -i" + p + " -o build/" + s + " " + p + "/" + s)

# the media files need to be copied to .HGamer3D
env.Command("build/.HGamer3D", "MediaFiles", [
			       Mkdir("build/.HGamer3D"),
			       "cp -r MediaFiles/* build/.HGamer3D"
			       ])