# SConstruct file to build Haskell packages
# #########################################

# set environment
#################
from os.path import expanduser
import os
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

# Gather main dependencies
##########################

dependsOn = [
	  "HGamer3D/Common.hs",
	  Glob("HGamer3D/Common/*"),
	  Glob("*.cabal"),
	  "LICENSE"
]

target = [ "dist/setup-config", Glob("dist/HGamer3D-*.tar.gz")]

env.Command(target, dependsOn, [

"ghc-pkg unregister HGamer3D || true",
"ghc-pkg unregister HGamer3D-Graphics3D || true",
"ghc-pkg unregister HGamer3D-InputSystem || true",
"ghc-pkg unregister HGamer3D-Network || true",
"ghc-pkg unregister HGamer3D-Audio || true",

"cabal configure --user",
"cabal build",
"cabal haddock",
"cabal install --user --extra-lib-dirs=" + home + "/.HGamer3D/lib",
"cabal sdist"
])
