# SConstruct file to build Ogre Haskell packages
# ##############################################

# set environment
#################
from os.path import expanduser
import os
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

# add c2hs location
env.AppendENVPath('PATH', home + os.sep + '.cabal' + os.sep + 'bin')

# Gather main dependencies
##########################

dependsOn = [
	  Glob("HGamer3D/Bindings/Ogre/*"),
	  Glob("*.cabal"),
	  "LICENSE"
]

target = [ "dist/setup-config", Glob("dist/HGamer3D-*.tar.gz")]

env.Command(target, dependsOn, [
"cabal configure --user --extra-lib-dirs=" + home + "/.HGamer3D/lib",
"cabal build",
"cabal haddock",
"cabal install --user --extra-lib-dirs=" + home + "/.HGamer3D/lib",
"cabal sdist"
])
