# SConstruct file to build Haskell packages
# #########################################

# set environment
#################
from os.path import expanduser
import os
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

# Gather main dependencies
##########################

dependsOn = [
	  Glob("HGamer3D/*"),
	  Glob("*.cabal"),
	  "LICENSE"
]

target = [ "dist/setup-config", Glob("dist/HGamer3D-*.tar.gz")]

env.Command(target, dependsOn, [
"cabal configure --user --extra-lib-dirs=" + home + "/.HGamer3D/lib",
"cabal build",
"cabal haddock",
"cabal install --user --force-reinstalls --extra-lib-dirs=" + home + "/.HGamer3D/lib",
"cabal sdist"
])
