# SConstruct file to build Haskell packages for InputSystem module
# ################################################################

# set environment
#################
from os.path import expanduser
import os
home = expanduser("~")
env = Environment() 
env["ENV"]["PATH"] = os.environ.get("PATH")
env["ENV"]["HOME"] = os.environ.get("HOME")

# Gather main dependencies
##########################

dependsOn = [
	  "HGamer3D/InputSystem.hs",
	  Glob("HGamer3D/InputSystem/*"),
	  Glob("HGamer3D/BaseAPI/*"),
	  Glob("*.cabal"),
	  "LICENSE",

	  Glob("../Data/dist/HGamer3D-*.tar.gz"),
	  Glob("../Common/dist/HGamer3D-*.tar.gz"),
	  Glob("../Bindings/SFML/hBuild/dist/HGamer3D-*.tar.gz"),

]

target = [ "dist/setup-config", Glob("dist/HGamer3D-*.tar.gz")]

env.Command(target, dependsOn, [

"ghc-pkg unregister HGamer3D || true",
"ghc-pkg unregister HGamer3D-Wire || true",

"cabal configure --user",
"cabal build",
"cabal haddock",
"cabal install --user --extra-lib-dirs=" + home + "/.HGamer3D/lib",
"cabal sdist"
])
